/**Problem 2
* Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be :
* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
* By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.
*/

#include "problems.h"
#include "result.h"
#include "timer.h"

Result PE::problem_002()
{
	timer::start();
	uint64_t fib_accumulated = 1;
	uint64_t fib_previous = 1;
	uint64_t fib_even_sum = 0;
	for(uint64_t prev_accum{}; fib_accumulated < 4000000; fib_previous = prev_accum)
	{
		prev_accum = fib_accumulated;
		fib_accumulated += fib_previous;
		
		if (!(fib_accumulated % 2))
		{
			fib_even_sum += fib_accumulated;
		}
	}
	timer::stop();
	return { "2.Even Fibonacci Numbers", fib_even_sum, timer::get_elapsed_seconds() };
}