/*
 * Consider all integer combinations of a^b for 2 <= a <= 5 and 2 <= b <= 5
 * If they are then placed in numerical order, with any repeats removed, we get the following sequence of distinct terms:
 * 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
 *
 * How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?
 */

#include <set>

#include "problems.h"
#include "result.h"
#include "timer.h"

Result PE::problem_029()
{
	timer::start();
	std::set<double> unique_results;

	for( uint64_t a = 2; a < 101; ++a )
	{
		for ( uint64_t b = 2; b < 101; ++b )
		{
			unique_results.emplace( pow( a, b ) );
		}
	}

	timer::stop();
	return { "29.Distinct Powers", get_result_string( unique_results.size() ), timer::get_elapsed_seconds() };
}
